# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
   include:
     - vote/**

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  GIT_TOKEN: $(GIT_TOKEN)  # Define your Git token as a pipeline variable
  GIT_USER: 'bhargavqwertyuiop'
  GIT_EMAIL: 'bhargavtejai123@gmail.com'
  REPO_URL: 'https://$(GIT_USER):$(GIT_TOKEN)@github.com/bhargavqwertyuiop/vote-app.git'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'connectiondocker'
        repository: 'bhargavqwertyuiop/vote'
        command: 'buildAndPush'
        Dockerfile: '**/vote/Dockerfile'
        tags: '$(tag)'
      
    - task: ShellScript@2
      inputs:
        scriptPath: 'update.sh'
        args: 'vote-app $(Build.BuildId) vote-deployment.yaml'
      env:
        GIT_TOKEN: $(GIT_TOKEN)

      
            
        
